feat:added trip group management

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,14 +15,14 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Validate Branch Name
+        if: github.event_name == 'pull_request'
         run: |
-          BRANCH_NAME="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
+          BRANCH_NAME="${{ github.head_ref }}"
           echo "Branch: $BRANCH_NAME"
 
           if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|chore|release)\/[A-Z]+-[0-9]+-[a-z0-9-]+$ ]]; then
-            echo "❌ Invalid branch name."
-            echo "Example: feature/TB-123-create-trip"
-            exit 1
+          echo "❌ Invalid branch name."
+          exit 1
           fi
 
       - name: Validate Commit Message
